import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer/Footer'
import Hero from '../components/hero/Hero'
import MemoryWrapper from '../components/memory-wrapper/MemoryWrapper'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Hero />
        <MemoryWrapper />
      <Footer />
      <div id="modals"/>
    </div>
  )
}

export default Home
